
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    whisper-large-v2-submod-2-time-3:
        namespace: cdgp
        lang: python3-http
        handler: ./whisper-large-v2-submod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-whisper-large-v2-submod-2-time-3:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "3.33s"
            write_timeout: "3.33s"
            exec_timeout: "3.33s"
            debug: "false"
            infer_device: "cuda"
    
    whisper-large-v2-submod-1-time-3:
        namespace: cdgp
        lang: python3-http
        handler: ./whisper-large-v2-submod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-whisper-large-v2-submod-1-time-3:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "6.67s"
            write_timeout: "6.67s"
            exec_timeout: "6.67s"
            debug: "false"
            infer_device: "cuda"
    
    whisper-large-v2-submod-0-time-3:
        namespace: cdgp
        lang: python3-http
        handler: ./whisper-large-v2-submod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-whisper-large-v2-submod-0-time-3:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    